[package]
name = "baekjoon"
version = "0.1.0"
edition = "2021"

[[example]]
name = "boj_3986"
path = "data_structures/boj_3986.rs"

[[example]]
name = "boj_1302"
path = "data_structures/boj_1302.rs"

[[example]]
name = "boj_18258"
path = "data_structures/boj_18258.rs"

[[example]]
name = "boj_17608"
path = "data_structures/boj_17608.rs"

[[example]]
name = "boj_2605"
path = "data_structures/boj_2605.rs"

[[example]]
name = "boj_2161"
path = "data_structures/boj_2161.rs"

[[example]]
name = "boj_10815"
path = "binary_search/boj_10815.rs"

[[example]]
name = "boj_1920"
path = "binary_search/boj_1920.rs"

[[example]]
name = "practise"
path = "practise.rs"